[theme]
primaryColor = "#F63366"  # Couleur principale (exemple ici : rose)
backgroundColor = "#F0F8FF"  # Couleur de fond de l'application (bleu clair)
secondaryBackgroundColor = "#e6f7ff"  # Couleur de fond de la barre latérale
